### ISSUE TITLE
Multilingual support?

### ISSUE THREAD

**Issue by leeper** [Ironholds/batman#1]
Great idea! How about multilingual support, either as a function argument or in response to the language environment?

**Comment by Ironholds** [comment]
Ooh, that'd be _really_ cool. You're the language nerd; wanna get me some examples? ;). I'll rewrite the guts to rely on a .RData.

**Comment by leeper** [comment]
Alrighty then. I'll try to track down a database of translations.

**Comment by Ironholds** [comment]
@leeper I more meant "if you could give me some Danish we can test and expand the set from there" but a language db would be awesome too!

**Comment by Ironholds** [comment]
@leeper okay, multilingual support now added - in the sense that the code and package structure allows for it. Check out batman::categorical_booleans !

I'm going to write up a rationale behind this package soliciting translations and throw it up on my blog/twitter/etc (since I only fluently speak English, although I can swear in _many_ languages). Iff you'd like to submit, say, Danish equivalents, that would be most appreciated (and if you'd like to further promote the request for translations that would be really really appreciated!)

**Comment by rubenarslan** [comment]
Yes/no
German/de: ja/nein
French/fr: oui/non
Turkish/tr: evet/hayır
Swedish/sv: ja/nej

True/false:
German: wahr/falsch
French: vrai/faux
Turkish: doğru/yanlış
Swedish: sant/falskt

But I guess people don't really talk use true/false in other languages..?

Anyway, just wanted to add Turkish because of https://en.wikipedia.org/wiki/Batman,_Turkey

**Comment by Ironholds** [comment]
Ahahah. Perfect :D. Yeah, local idiomatic equivalents would be really appreciated, as well as the direct values.

**Comment by Ironholds** [comment]
Now email me your address if you want a sticker!

**Comment by cakiki** [comment]
Yes / No
Hungarian: Igen / Nem

True / False
Hungarian: Igaz / Hamis

**Comment by Ironholds** [comment]
Added, ditto sticker question ;)

**Comment by leeper** [comment]
Castilian Spanish (es):
yes/TRUE: sí, cierto
no/FALSE: no, falso

Danish (da)
yes/TRUE: ja, sandt
no/FALSE: nej, falsk

Maybe add a CONTRIBUTING file to make clear how people can add translations?

Also, in English, you have the digits 1 and 0, and the word "none". Do you want the words "one" and "zero"/"none" in other languages?

**Comment by petermeissner** [comment]
German: 
True / Yes / ... : wahr, 1 / ja, ok
False / No / Absent... : falsch, 0 / nein / kein, keins, null

Also I would maybe consider the good old (and I believe international): "x" versus "" dichotomy

**Comment by ilapros** [comment]
Italian 
Yes/no/maybe
si/no/forse

TRUE/FALSE
Vero/Falso

For survey the missing value is generally something that is translated to doesn't know/ doesn't answer: non sa/ non risponde 

One more obvious dichotomy in surveys is male/female (which is a very restrictive dichotomy...) - not sure if batman can/will handle that as well.

**Comment by mine-cetinkaya-rundel** [comment]
@rubenarslan Turkish yes should be evet, not ewet.

**Comment by Ironholds** [comment]
Thanks all! 

Missing values aren't as necessary since values not recognised as TRUE/FALSE are going to end up NA anyway (it's the nature of how booleans work).

On male/female; that's a false societal dichotomy that is all too often used to weld gender identity to biology (and doesn't get biology right either). Equating all possible ways of phrasing questions around gender identity (respectful or no) with a single respectful middle-ground seems damn hard - and I like my science inclusive and respectful. So I'd rather hold off until the point where humanity comes up with a good set of equivalencies and a single uniform way of representing those positions on the scale of gender identity.

**Comment by rubenarslan** [comment]
@mine-cetinkaya-rundel oops, grandma will be aggravated.
@Ironholds also, in lots of data m/f is often ambiguous: mother/father or male/female

**Comment by minisciencegirl** [comment]
Chinese - 
Yes: 是/ 對 / 对 / 對的 / 对的
No: 不/ 不是 / 不對 / 不对/ 唯

True: 对/ 對的 / 正确的 / 真正的 / 對 
False: 错/ 錯的 / 錯誤的 / 不對 / 錯

**Comment by Ironholds** [comment]
@minisciencegirl thanks! Would you like real-name credit or pseudonym credit?

**Comment by adolfoalvarez** [comment]
Yes/no:
Spanish : si/no
Polish: tak/nie

True/false:
Spanish: cierto/falso, verdadero/falso, V/F
Polish: prawda, fałsz

**Comment by minisciencegirl** [comment]
Real name credits sound great! Thank you!
